### ISSUE TITLE
OpenVDC log doesn't work with remote mesos

### ISSUE THREAD

**Issue by Metallion** [axsh/openvdc#108]
### Problem

The `openvdc log` command ignores the mesos master IP address set in the openvdc config file.

```
[kemumaki@executor ~]$ cat .openvdc/config.toml

[api]
endpoint = "10.0.100.12:5000"
[mesos]
address = "10.0.100.11:5050"

[kemumaki@executor ~]$ openvdc log i-0000000001
FATA[0000] Couldn't connect to Mesos master              error="dial tcp 127.0.0.1:5050: getsockopt: connection refused"
```

### Solution

Get the `openvdc log` command to use the mesos address value set in the config file if it's defined.

**Comment by b0r6** [comment]
Isn't the field name in your config file wrong though?

[mesos]
master = "10.0.100.11:5050"

**Comment by Metallion** [comment]
Done.
