### ISSUE TITLE
LXC executor currently requires virbr0 bridge

### ISSUE THREAD

**Issue by Metallion** [axsh/openvdc#109]
### Problem

On a standard installation `/etc/lxc/default.conf` contains the following line.

```
lxc.network.link = virbr0
```

The `default.conf` file is included in every `/var/lib/lxc/<container-name>/config` file. That means LXC will never work unless the user first create a bridge called `virbr0`.

### Solution

We can not touch the `/etc/lxc/default.conf` file. Users might have created their own default conf for LXC and we can't just let OpenVDC modify that behind their back. We have to get containers started by OpenVDC to ignore the default configuration.

* First figure out if there's an option to ignore default conf in the library we're using.
* If not, completely overwrite `/var/lib/lxc/<container-name>/config` after it gets created with the default conf contents in it.

**Comment by b0r6** [comment]
This is addressed in the lxc-networking branch. <strike>But yeah, indeed it's not good practice to tamper with the default.conf file, so I'll make some changes.</strike>

Edit: Nvm, actually the default.conf is never edited. The config files get modified after the container is created.
