### ISSUE TITLE
Instance stuck on `STARTING` if no internet access on executor

### ISSUE THREAD

**Issue by Metallion** [axsh/openvdc#156]
### Problem

When you start an instance but the executor instance does not have access to the internet, the instance will never come up and its database entry will be stuck in `STARTING` state forever.

### Reproduction

* Install `openvdc-cli` on machine A.
* Install `openvdc-executor-lxc` on machine B.
* Set it up so machine A and machine B have network access to each other but machine B does not have internet access. For example remove its default gateway from the routing table.
* On machine A: 

```
A $ openvdc run centos/7/lxc
INFO[0000] Updating registry cache from https://raw.githubusercontent.com/axsh/openvdc/master/templates
INFO[0002] Found template: centos/7/lxc
i-0000000000
```
* On machine B:

```
B $ lxc-info -n i-0000000000
i-0000000000 doesn't exist
```

* On machine A:

```
A $ openvdc show i-0000000000
{
  "iD": "i-0000000000",
  "instance": {
    "id": "i-0000000000",
    "slaveId": "91fb613c-2abf-477a-b41c-41b37e1845b9-S0",
    "lastState": {
      "state": "STARTING",
      "createdAt": "2017-04-17T06:48:54.339487647Z"
    },
    "createdAt": "2017-04-17T06:48:48.379337475Z",
    "template": {
      "templateUri": "https://raw.githubusercontent.com/axsh/openvdc/master/centos/7/lxc.json",
      "lxc": {
        "lxcTemplate": {
          "template": "download",
          "distro": "centos",
          "release": "7"
        }
      },
      "createdAt": "2017-04-17T06:48:48.379337475Z"
    }
  }
}
```

Instance `i-0000000000` is now stuck in this state forever.

### Suggested solution

I would suggest a `FAILED` state which is identical to `TERMINATED` except it happened because of an error and not because a user called `openvdc destroy`. Something like this:

```
 $ openvdc show i-0000000000
{
  "iD": "i-0000000000",
  "instance": {
    ...
    "lastState": {
      "state": "FAILED",
      "Reason: Failed to download lxc template: <whatever error message golang gave us>"
      ...
    },
  ...
}
```

**Comment by unakatsuo** [comment]
agree with the solution. will start the new PR for this issue.

**Comment by unakatsuo** [comment]
![instance-state](https://cloud.githubusercontent.com/assets/95236/25085042/05de3972-239b-11e7-9b08-5e368f7c6234.png)

**Comment by Metallion** [comment]
Confirmed fixed.
