### ISSUE TITLE
Yum repo garbage collection

### ISSUE THREAD

**Issue by Metallion** [axsh/openvdc#54]
### Problem

Currently the CI just pushes yum repositories for every commit and they stay online forever. We need a periodically running jenkins job to clean those up.

### Current state

In https://ci.openvdc.org/repos/ there are a lot of folders named something like `20161223124709gitb06bd3`.

After https://github.com/axsh/openvdc/pull/52 is merged that format will change and instead a directory will be made for every branch.

### Suggested solution

Add a new jenkins job whose sole purpose is garbage collection. It should assume the new way of working from https://github.com/axsh/openvdc/pull/52. The old `20161223124709gitb06bd3` can be removed manually after waiting a few weeks so we're sure no more code depends on them.

* The garbage collection job should run periodically. Either every night or every weekend?
* For every branch that has a yum repository it should do the following checks:
  - Is this branch still on github?
    + If **no**: delete!
    + if **yes**:  Has this branch been comitted to in the last 2 weeks? (probably best to make the 2 weeks period configurable)
      - if **no**: delete!
      - if **yes**: do nothing.

**Comment by Metallion** [comment]
Another detail I forgot to add here. The `master` and `develop` branches should never be removed.

We don't have a `develop` branch yet but once we do stable releases, we will put the stable code on `master` and the development code on `develop` like we're doing for Wakame and OpenVNet.

**Comment by akirapop** [comment]
A pull request has been made for this issue. Rpm repos are removed as per the above prescription: no longer existing branches and branches that have not been "pushed" to in 2 weeks are removed. All repos. in master that are older than 2 weeks are removed UNLESS THE REPO IS THE CURRENT (sym. linked to "current") RPM!
