### ISSUE TITLE
Executor has local configuration file.

### ISSUE THREAD

**Issue by unakatsuo** [axsh/openvdc#79]
``openvdc-executor`` is requiring local specific configuration parameters, such as bridge/openvswitch name.

The change could be similar to  #64.

- [ ] Switch the flag library to ``spf13/cobra``
- [ ] Load ``/etc/openvdc/executor.conf`` at startup using ``spf13/viper``. Remove global variables for the old flag and replace to ``viper.Get***()``.

**Comment by Metallion** [comment]
Done.
