### ISSUE TITLE
Garbage Collection: Docker images

### ISSUE THREAD

**Issue by Metallion** [axsh/openvdc#83]
### Problem

Unit tests, rpmbuild and acceptance test are all running in Docker containers. The containers themselves are being cleaned up after the test runs but their images remain.

Removing the images along with the containers would not be the right thing to do because Docker uses those as cache. Leaving them all alone would just keep eating up disk space. We have to find the correct middle ground.

### Current state

The Jenkins slave where the unit tests and rpmbuild jobs are running currently has a bunch of images lying around.

```
[vagrant@localhost ~]$ sudo docker images
REPOSITORY                                          TAG                 IMAGE ID            CREATED             SIZE
citest.acceptance-test.el7                          latest              da2a9e39c5c9        6 days ago          682.8 MB
citest.console-service.el7                          latest              da2a9e39c5c9        6 days ago          682.8 MB
unit-tests.citest.acceptance-test.el7               latest              ed39a2d02d4d        6 days ago          890.1 MB
unit-tests.citest.console-service.el7               latest              ed39a2d02d4d        6 days ago          890.1 MB
unit-tests.citest.lxc-networking.el7                latest              ed39a2d02d4d        6 days ago          890.1 MB
unit-tests.citest.master.el7                        latest              ed39a2d02d4d        6 days ago          890.1 MB
unit-tests.citest.protoc-go-generate.el7            latest              ed39a2d02d4d        6 days ago          890.1 MB
unit-tests.citest.remove-old-integration-test.el7   latest              ed39a2d02d4d        6 days ago          890.1 MB

...
```

Some times @unakatsuo is logging in and deleting them manually.

On the acceptance test slave, we are only just starting to use docker so there's only a few images at the time of writing.

```
[18:26:04] metallion@phys028  (~) > sudo docker images
REPOSITORY                TAG                                        IMAGE ID            CREATED             SIZE
openvdc/acceptance-test   acceptance-test.20170119064535git276b558   2546af339d82        13 minutes ago      466 MB
docker.io/centos          7                                          67591570dd29        4 weeks ago         191.8 MB
```

### Solution

It's very tempting to just remove all images that are (for example) two weeks old. Some things have to be considered though.

* It's possible that containers are still up because the `LEAVE_CONTAINER` flag was set. Whenever somebody sets that flag, it should be their responsibility to clean up after they're done.

* What if the `docker rmi` command fails because some things are still dependent on an old image?

Maybe we can just try to implement the garbage collection as simple as possible and then see what complications come up? For that I would suggest to just run nightly and remove every image that is over 2 weeks old. Just like in the other GC jobs, that time should be configurable.

**Comment by akirapop** [comment]
@Metallion, just to be clear: These images are on the vm, correct? (The jenkins master.)

There are docker images on this machine, and also on .28. The cleanup is on the master?

**Comment by akirapop** [comment]
This branch will be ready to go, once the cache_cleanup branch is merged. (This branch requires being merged with the code in cache_cleanup.)

**Comment by Metallion** [comment]
Done.
